### ISSUE TITLE
Should this repository be archived?

### ISSUE THREAD

**Issue by dellagustin-sap** [InnerSourceCommons/innersourcecommons.net#10]
This is a follow up of the thread I started on slack: https://innersourcecommons.slack.com/archives/CGSE508A1/p1582733537020700

This repository is very similar to https://github.com/InnerSourceCommons/innersourcecommons.org, but I could not understand its current purpose.
It would be interesting to archive it, if it does not have a use anymore.

**Comment by maxcapraro** [comment]
That's a good question. It can potentially be archived. At the very minimum, we should let people know that this is not the real website (#11).

Good finding @dellagustin-sap, thank you! :)

**Comment by voborgus** [comment]
New life for this repo: work on the new version of the site.
