### ISSUE TITLE
Change behavior and the flag of the language button

### ISSUE THREAD

**Issue by voborgus** [InnerSourceCommons/innersourcecommons.net#21]
**Is your feature request related to a problem? Please describe.**
The language button by default yells with the Russian flag. But the default language is English.

**Describe the solution you'd like**
Make this button to work as for example in [Kubernetes documentation](https://kubernetes.io/docs/home/) or [here](https://wpml.org/documentation/)

**Additional context**
Button code located at `layouts > partials > header.html` file and settings file on the root `config.yaml`. Will be great if the standard functionality of the Bootstrap CSS will be used. US flag should be changed to neutral English form, maybe just to replace flags with text.

**Comment by spier** [comment]
What feature is behind that flag button?

If if it meant to be a translation function for the whole site, we could leave this way completely for now, as we only have English content for now. i.e. removing the whole button.

**Comment by voborgus** [comment]
```
What feature is behind that flag button?
```

Yep, this Is a translation function. We already have many languages in the learning path section.

In addition, my personal plan is to translate the main pages of the site to Russian and ask the community to do the same to some popular languages too. It will be possible after some early finalization of the content on the main pages.

**Comment by spier** [comment]
Ah. I forgot about the learning path.

Could we limit the translation/flag feature just to the learning path section then for a first release of the new site? Otherwise the creation of the translations will become a blocker for the release.

**Comment by voborgus** [comment]
Decided to go without flags. [reason](https://jkorpela.fi/flags.html)
