### ISSUE TITLE
Add a chapter with companies practice InnerSource

### ISSUE THREAD

**Issue by voborgus** [InnerSourceCommons/innersourcecommons.net#22]
**Is your feature request related to a problem? Please describe.**
Now it's unclear what companies applies InnerSource approaches in their work.

**Describe the solution you'd like**
Collect & put companies logos on the home or about page. Maybe to concatenate this with the survey results.

**Comment by spier** [comment]
One example of a very simple format for a list of adopters:
https://github.com/backstage/backstage/blob/master/ADOPTERS.md

**Comment by voborgus** [comment]
The starting point for this task can be the regular Danese's slide: https://youtu.be/ddlb3gh4WwE?t=925

**Comment by clcoffey** [comment]
Can we name this page "InnerSource in Action" and place it under Learn in between Books and Learning Path? Katie compiled a list of companies and quotes to go on this page that we can populate later.

**Comment by spier** [comment]
I for one like the name **InnerSource in Action**.
Sounds like something with force :)

**Comment by voborgus** [comment]
Great! The list of companies with quotes is the right what is needed in our site to prove InnerSource adoption.
IMHO, it’s not clear before opening what is the content located in the section with the name “InnerSource in action”. Maybe **Companies** section in the root menu level will be more clear?

**Comment by claredillon** [comment]
The plan for that page is the place for the future to put all evidence we have regarding use of InnerSource:

- Logos of companies who have declared in public they are using InnerSource
- Quotes from articles and videos we have 
- Links to podcasts/videos/case studies we hope to create in the future (outside the context of the summits). 

I love "InnerSource in Action" as a link as well - maybe something to check with a wider audience as to what fits best for people. 

Are there other options/ideas other than "InnerSource in Action" or "Companies" we could include?

**Comment by Katiegilroyy** [comment]
Hi All, Here is the list of companies that have stated they are using InnerSource with links to where they made the statements 
I like the name "InnerSource In Action"
https://docs.google.com/document/d/1CwkYscAoEahVnwLjjdwTC-4jxc_kHI_HdVwpMP0H_sI/edit?usp=sharing

**Comment by voborgus** [comment]
Decided: let’s go with “InnerSource in Action” :)

Any thoughts about the placing of this page? A have doubts for the “Learn” section... If we’ll think in a way that people will "learn" about InnerSource on this page then it will be possible to mark any page on the site as a page promoting learning :)

**Comment by claredillon** [comment]
I was thinking of it as "learn where InnerSource is used" - and we will be including insights into how people are using InnerSource in the future... But happy to consider other places. 

It will be a high profile page in the future - as a destination for a lot of our outreach work aimed at changing behaviour / raising awareness starts with celebrating third party case stories/ evidence of InnerSource use.

On the learning/change path at an organisational level - "who's doing it today?" typically gets asked before "how do I get started?". I see the Learn tab as the place for all our resources that helps people on the path to InnerSource, including the evidence pieces.

**Comment by voborgus** [comment]
https://innersourcecommons.net/community/action/ @clcoffey

**Comment by clcoffey** [comment]
Hi Dmitrii, I am not sure how this happened but this page used to have a picture at the top with all the logos of the companies that are using InnerSource. We will have to add them back somehow, maybe at the bottom. It would be great if we could find a way to add them one by one rather than all of them in one picture.

**Comment by voborgus** [comment]
Yeah as you can see in the code I've done some changes with coding and now there is the special `{{< company >}} `tag exists. Let's try to list all separate logos in that way:

```
      {{< company name="PayPal" image="/images/logos/paypal.png" >}}{{< /company >}}
      {{< company name="PayPal" image="/images/logos/paypal.png" >}}{{< /company >}}
      ...
```

**Comment by clcoffey** [comment]
Oh that's brilliant! Thanks Dmitrii!

**Comment by voborgus** [comment]
I think keeping all logos in separate files will be great for being able to add new companies easily in the future.

**Comment by clcoffey** [comment]
Yes, you are right! :-)

**Comment by claredillon** [comment]
I've made a change to clarify that the list is about people who have publicly referenced their InnerSource usage (note they are not necessarily part of ISC): https://github.com/InnerSourceCommons/innersourcecommons.net/pull/64 

The page looks great BTW - thanks @voborgus, @clcoffey and @Katiegilroyy. We probably can close this issue now.
