### ISSUE TITLE
Describe the membership process 

### ISSUE THREAD

**Issue by voborgus** [InnerSourceCommons/innersourcecommons.net#23]
**Is your feature request related to a problem? Please describe.**
It’s unclear now what is the membership and  how to become an ISC member.

**Describe the solution you'd like**
Create a section with the details of the ISC membership.

**Additional context**
Maybe to combine somehow with details on the about page.

**Comment by claredillon** [comment]
How to join the community is included on the Community page - will work on the description of ISC Membership in the About Us section.

**Comment by claredillon** [comment]
High level outline of the Membership process now in About page. https://innersourcecommons.net/about/
