### ISSUE TITLE
Upload incorporation documents from the old site

### ISSUE THREAD

**Issue by voborgus** [InnerSourceCommons/innersourcecommons.net#24]
**Describe the solution you'd like**
Upload incorporation documents to the about section.

**Additional context**
Old place is here: 
http://innersourcecommons.org/board/

**Comment by spier** [comment]
If I understand this correctly, this issue is about taking all the content from http://innersourcecommons.org/board/ and recreating it at https://innersourcecommons.net/about/board/. Correct?

i.e. the content that is being moved is:
- list of board members
- incorporation documents (bylaws)
- Public Board Meeting Notes

**Comment by voborgus** [comment]
It's up to a committer to decide the best way of the content organization :) 

Just FYI, some info about members is already here but can be moved in a better place: https://innersourcecommons.net/about/innersourcecommons/

> Public Board Meeting Notes

Is there a way to get rid of this dynamic content from the site? Is it a legal restriction that we need to keep and feed this on the site?

**Comment by spier** [comment]
I could not figure out yet if publishing these meeting notes is strictly required.
I checked the bylaws I could find anything about that there either.

Will confirm with some others before I proceed.

**Comment by spier** [comment]
I got confirmation from Danese that we want to keep the terse notes around.
So we should expect that after each Board meeting somebody would create a new file with terse meeting notes for that meeting.

**Comment by claredillon** [comment]
For the record, here are some details on the legal requirements for US nonprofits from a hand blog post: https://boardable.com/blog/board-meeting-minutes/ 


The IRS and most state laws (section 3.151 of the Texas Business Organizations Code) require that corporations, including nonprofit corporations, keep copies of their meeting minutes.

From https://boardsource.org/resources/board-meetings-faqs/: 

What should be included in the minutes of a board meeting?
While content can vary, based on your individual organization, the basic elements of board meeting minutes should include the following:


Name of the organization
Date and time of meeting
Board members in attendance, excused, and absent
Existence of a quorum
Voting results
Names of abstainers and dissenters
Reports and documents introduced
Future action steps
Ending time of meeting
Signature of the secretary
Some boards also include motions made and by whom, and a brief account of any debate. Your board should determine how much detail is desirable without cluttering the document with irrelevant data.

**Comment by voborgus** [comment]
https://innersourcecommons.net/about/board/

Can we have also a one-paragraph text at the top of the page explaining the purpose of the board?

**Comment by spier** [comment]
> https://innersourcecommons.net/about/board/
> 
> Can we have also a one-paragraph text at the top of the page explaining the purpose of the board?

The original purpose of this ticket was to upload the incorporation documents (bylaws).
This has already been achieved, plus a lot more.

Therefore i would vote for opening a new ticket about "intro text" explaining the purpose of the Board.  And then closing this tickt here. That also allows us to reprioritize the new issue (i.e. is it MVP or not?)

Thoughts?

**Comment by voborgus** [comment]
Closing this, continue in #55
