### ISSUE TITLE
Autogenerate Learning Path files from their repository

### ISSUE THREAD

**Issue by voborgus** [InnerSourceCommons/innersourcecommons.net#28]
**Is your feature request related to a problem? Please describe.**
Some refinements should be done to be able to consume the markdown files in the new site.

**Describe the solution you'd like**
Put the new documents into the [learning](https://github.com/InnerSourceCommons/innersourcecommons.net/tree/master/content/learning) folder as sub-folders.

**Important notice**: The old site rendered the learning path content with the JS file during the build. Now there is no need to generate HTML during the build – the only conversion to `*.md` and meta information enrichment is needed. These markdown files should be pushed to the site repository with the right structure:

* All thumbnails should go to `static/images/learn`
* All learning paths content should go to the `content/learning` folder
* All course files should go to their own directory with their own names, like: `introduction` or `contributor`
* Each course should have a new index file should be named as `_index.md` 
and should have additional meta 
```
image: "images/learn/LP_thumbnail_introduction.jpg"
featured: true // only for the first main starting object
```
and a short text description.

* Content files should **contain the text course information** and be enriched with additional metadata:
```
image: "images/learn/LP_thumbnail_introduction.jpg"
weight: 2 // to have materials to be ordered
youtubeCode: "v9fL-E3ZVdc"
``` 
* Other language files should be marked with the short two-letters language name in the file name postfix before the extension of the file. For example: `01.md` should be `01.ru.md`

Example course structure (to be rewritten by your script): 
https://github.com/InnerSourceCommons/innersourcecommons.net/tree/master/content/learning/introduction

**Comment by tsadler1988** [comment]
Hi @voborgus, I've started working on this in #32. There a few issues I've raised that could do with your input please :)

**Comment by voborgus** [comment]
We should ask the WG's `OK` before going live with the new site.

**Comment by voborgus** [comment]
The issue was done in #32 
Available here: 
https://innersourcecommons.net/learn/learning-path/

Still need to tackle translations and GitHub Actions in another issue.

Closing this; will continue at #51
