### ISSUE TITLE
Create a page "what is InnerSource"

### ISSUE THREAD

**Issue by voborgus** [InnerSourceCommons/innersourcecommons.net#29]
**Is your feature request related to a problem? Please describe.**
It’s impossible now to answer on someone’s question “what is InnerSource” with the link to the site

**Describe the solution you'd like**
Create a single page explaining the basics. Enrich this page with some images.
Create a link on the home page to that page.

**Comment by claredillon** [comment]
Do we need this for the MVP? Does pointing to the learn page not give people the way in which they can learn more about what is InnerSource etc.?

We do give the basic definition in the first paragraph on the home page.

**Comment by claredillon** [comment]
On the new Learn Index page, I've now explicitly listed the Learning Path Introduction as the place to go to learn about the basic InnerSource principles. I don't think we need any more for the MVP.
