### ISSUE TITLE
Check and improve text on the site

### ISSUE THREAD

**Issue by voborgus** [InnerSourceCommons/innersourcecommons.net#30]
**Is your feature request related to a problem? Please describe.**
Since my language skills are far away from the native, some checks should be done. Also, some marketing improvements can be applied to the text.

**Describe the solution you'd like**
Scan through pages and burn a bad stuff.

**Comment by spier** [comment]
@voborgus I added the MVP tag, as doing this prior to launch seems important. Feel free to remove it again if you disagree.

**Comment by claredillon** [comment]
Breaking the issue up to help us show progress and not duplicate checks:

- [ ] Home page
- [ ] Learn pages
- [ ] Events pages
- [ ] Community pages
- [ ] About pages

**Comment by claredillon** [comment]
I've done a review  - made a couple of small changes (some to be reviewed/committed, where I have done anything more than small grammar changes) - and looks all good to my Hiberno-English eyes! :) Might be good to have a second review before we go live.

**Comment by claredillon** [comment]
@Katiegilroyy reviewed as well - so with two reviews complete, closing this issue.
