### ISSUE TITLE
Move the ISC-101 to the website

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/innersourcecommons.net#31]
**Is your feature request related to a problem? Please describe.**

The Google doc that contains the ISC 101 info currently lives in my gDrive account.
That can be problematic if anybody other than me wants to make changes to it.

http://innersourcecommons.org/isc-101

**Describe the solution you'd like**

Therefore I would vote to move this content somewhere else.
Maybe we could have this content somewhere on the new ISC website?

**Comment by voborgus** [comment]
great!

@claredillon can you look on this issue please and see where in the current structure of the site this can be placed?

**Comment by claredillon** [comment]
Sounds fab. Thanks Sebastian. I'll review the doc and incorporate it into either the Community and/or the About ISC pages, as appropriate.

**Comment by spier** [comment]
Thanks. 

The important piece for me about this is:
Once I decide that the ISC is an interesting community for me to get involved with, I want to know roughly how things work. Not in every last detail but I want to have a good idea what the different "things" in the community are. Being able to see that "at a glance" is helpful for me.

Think similar to the first 2 pages of an onboarding handbook that a new employee might get when joining a company.

So if you end up splitting this content about over multiple pages, please double check if the onboading experience for a new person is still enjoyable.

**Comment by claredillon** [comment]
I've put a (slightly abbreviated) version of this content from the 101 into the text for review for the Community page (description of working groups, principles of how we work, tools etc.). @spier will tag you to take a look once I get it into GitHub.

**Comment by spier** [comment]
@claredillon happy to review it once you point me to it. 

What format do you have the community page in?
I have a tool that I use to convert gDocs/docx to markdown. So if that would speed things up let me know and I am happy to help.

**Comment by claredillon** [comment]
Thanks @spier. I'm looking at the different templates Hugo gives for layout first, which is what is delaying me - but (in the interest of MVP deadlines ;) - if it doesn't work in the next day or two - I'll come calling for that tool. Though maybe you can leave a link here anyways for future reference! :)

**Comment by claredillon** [comment]
I've added a pull request to create a community.md file which incorporated most of the InnerSource 101 doc.

https://github.com/InnerSourceCommons/innersourcecommons.net/pull/41

**Comment by voborgus** [comment]
https://innersourcecommons.net/community/

**Comment by spier** [comment]
@voborgus I have some improvements to push to this page. Would you mind adding me as a contributor to the repo, so that I can create a branch here directly?

**Comment by voborgus** [comment]
@spier for sure, you’re in 👍🏻

**Comment by spier** [comment]
Based on what I see at https://innersourcecommons.net/community/ I would consider this issue done, and we can close it if you agree.
