### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/innersourcecommons.net#34]
**Is your feature request related to a problem? Please describe.**

We will need to include a Privacy Policy on the website that is in line with GDPR regulation. 

**Describe the solution you'd like**

I am not familiar with GRPR and privacy policies. Has anyone looked into this before and can help with information on what needs to be included and potentially provide a first draft?

Things I think will be relevant and might need to be included: 
- cookies
- Personal data such as email and any other information we will request when asking people to join our mailing list
- Does joining the slack channel need to be included in the privacy policy? I know Whatsapp groups are not complying with GDPR regulations. Is this the case with Slack as well?

**Comment by clcoffey** [comment]
I have created a first draft of the Privacy Policy Here: https://docs.google.com/document/d/1U_q8MCSk_bbyqq6YJ_Yi5VDRCaIsDDAZXgsirBWMpqk/edit# I would appreciate any feedback you might have.

**Comment by claredillon** [comment]
Things to check:
- check we don't claim to be accessible. 
- check our level of commitment to change if there are issues. 
- ask @lenucksi to review - as he has an interest in this area too.
-

**Comment by voborgus** [comment]
Live on the site. Feel free to reopen if any case.
