### ISSUE TITLE
Create Page "Articles" and list it under Learn in the menu

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/innersourcecommons.net#35]
**Is your feature request related to a problem? Please describe.**
The previous website contains a list of Articles and external resources: https://innersourcecommons.org/resources/articles/ 

**Describe the solution you'd like**
Add a new page to the website called Articles
Populate the page with the content from the previous site: https://innersourcecommons.org/resources/articles/
Add a sub item "Articles" in the main menu under Learn (See screenshot attached with regards to positioning) 

**Additional context**
![Screenshot 2021-02-11 at 17 09 30](https://user-images.githubusercontent.com/78749459/107675424-00d54780-6c90-11eb-9f9c-d84cd8f981e0.png)

**Comment by voborgus** [comment]
On the site now.

https://innersourcecommons.net/learn/articles/

Ideas to improve:

* Change the image to something less stamp-y and more colorful. Like [this](https://unsplash.com/photos/bw-xiGR_hCU) or [some of this](https://pixabay.com/ru/images/search/zebra/) or even photo from the summit:

![image](https://user-images.githubusercontent.com/9394918/108032808-148ffd80-7044-11eb-8d47-6c182b6dfae0.png)

* think about this page as a potential place to be outdated:

1. Who will update this page in the future? In what frequency?
1. What is the value of this page if it will be outdated?
1. Who will read more than 5 years old articles?
1. Is it possible to move this to some social network?

**Comment by clcoffey** [comment]
These are all great questions! Let's address them in this evening's call.

**Comment by claredillon** [comment]
Agreed at the call yesterday evening:
We will move the articles under the Research page.
We will request that our community members involved in academic research keep it up to date.
This is not a requirement for the MVP.
We will delete the articles page and menu item.

**Comment by claredillon** [comment]
Note all ad hoc magazine references etc. will be posted in the social media channels and tagged.

**Comment by claredillon** [comment]
Also - for completeness, worthwhile recording the following:

It was noted that even older academic articles are of interest to the research/academic audience and form an important part of their process to decide that InnerSource is a valid endeavor. We do want to continue to have a listing of such academic articles on ISC website.

**Comment by voborgus** [comment]
Just scanned articles we have on https://innersourcecommons.net/learn/articles/ – seems there are no academic papers present in the list. 

Can someone re-check that to be able to delete this page?

**Comment by claredillon** [comment]
I have not included it in the new Learn Index page - @voborgus recommend we delete from the MVP and consider if/how to incorporate these in the future. 

Idea - we might do a 20 years of InnerSource look-back article including all the old article links (to have the archive on record) and then decide to use social channels (appropriately tagged) to track them moving forwards.

**Comment by claredillon** [comment]
I didn't mean to close this - sorry - I guess we should only close once we have deleted the Articles page/menu item.

**Comment by voborgus** [comment]
Can I remove the page & menu item now?

**Comment by claredillon** [comment]
@voborgus Yes please. And then we can close this! :)

**Comment by voborgus** [comment]
Done.

The backup archive can be found here: 
https://github.com/InnerSourceCommons/innersourcecommons.net/blob/acd3d0def62f40ff743d12ec0db8c3f93171904e/content/learn/articles.md

Let's continue in another issue. Sorry @clcoffey for the work done here :(
