### ISSUE TITLE
Rename News and Events Page to just Events

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/innersourcecommons.net#36]
**Is your feature request related to a problem? Please describe.**
Currently the News & Events section is only displaying Events, therefore would it make sense to rename it to just Events and in the future, when we will add press releases to the platform we could add the News section in?

**Describe the solution you'd like**
Change the name of News & Events to just Events

**Comment by voborgus** [comment]
PR merged, thanks!
