### ISSUE TITLE
Include a Code of Conduct Page

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/innersourcecommons.net#40]
We need a separate code of conduct page that we can refer to in various events and locations. 

Basis for this is the code of conduct already linked from our older events page. 

Propose we update/change to look more like the contributor code of conduct here: https://www.contributor-covenant.org/version/2/0/code_of_conduct/

This should go under the About Us Tab

**Comment by voborgus** [comment]
https://innersourcecommons.net/about/codeofconduct/
