### ISSUE TITLE
Create a Community folder/ menu item.

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/innersourcecommons.net#42]
**Is your feature request related to a problem? Please describe.**
We want to have a clear call to action for people who visit the site to get involved with the community. Vast majority of visitors will only passively consume the resources under Learn. This menu item points visitors to easy steps to get connected with other community members and gives an overview of the working groups so they can get more involved in the work.

**Describe the solution you'd like**
Please create a Community folder with corresponding menu item to appear in between Learn and Events on the menu.

**Additional context**
I've created a placeholder community.md file under About folder - this will be the index file in this new folder.

**Comment by voborgus** [comment]
👌🏻 https://innersourcecommons.net/community/ done
