### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by voborgus** [InnerSourceCommons/innersourcecommons.net#46]
**Is your feature request related to a problem? Please describe.**
It's unclear what should be placed under the "About" menu item. (https://innersourcecommons.net/about/)

**Describe the solution you'd like**
Decide what to do with that page.

Check content from https://innersourcecommons.net/about/commons/ and remove that link (merge with /about/).
The possible decision can be is completely removing the "About" page – but then we need to rethink the structure of the site and menu.

**Comment by claredillon** [comment]
I'll look at this today - there are some details about the foundation etc. that need to be included as well. 
Propose we merge with /about/ as suggested.

**Comment by Katiegilroyy** [comment]
Would you be able to put [this ](https://docs.google.com/document/d/1GDOprQ2CtkPhB7WsUPmfkvUa8QSHF4-V0rQj-JyQjME/edit?usp=sharing) information in the contact us part of the about page, doesn't have to be exactly like the picture just in a similar format

**Comment by voborgus** [comment]
Thanks for collecting this information!

Just curious, what is the purpose to put physical mail address there? In my opinion, since this is community page there is no physical space where we all sitting :)

**Comment by claredillon** [comment]
Have created the /About index page to give an overview of the ISC as a foundation, describing the formal corporation structure, how we work (license for site content, Membership, board and governance.

Propose now removing https://innersourcecommons.net/about/commons/

**Comment by claredillon** [comment]
Regarding the mail address question - put it in as sometimes people still need to post stuff, but more likely, people look for it to put in legal agreements. It's the formal address of the corporation - happy enough to leave it out....

**Comment by claredillon** [comment]
Closing this issue as the About Page now live.
