### ISSUE TITLE
Intermediate page for Patterns

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/innersourcecommons.net#47]
**Is your feature request related to a problem? Please describe.**

The old page contains some content related to patterns and the Patterns office hours. See:
* https://innersourcecommons.org/resources/patternsofficehours/
* and a bit https://innersourcecommons.org/resources/

**Describe the solution you'd like**

Integrate the old content in a new page at `/learn/patterns`

**Comment by spier** [comment]
I am considering this part of the MVP, as otherwise we would loose all info about the Patterns Office hours.

**Comment by voborgus** [comment]
Good to know,
and btw, the schedule [here](https://innersourcecommons.org/resources/patternsofficehours/) contains all community meetings. Maybe should go to the community page.

The content itself can go to the [community page](https://innersourcecommons.net/community/), patterns wg section too
(if you consider avoiding intermediate page creation).

**Comment by voborgus** [comment]
My thoughts on this point:
Under the learning section, we should keep only the content produced by the working group. I mean the pattern itself from Patterns WG, the learning path from the corresponding WG.
Other info: office-hours, organization moments, etc should live under the [community section](https://innersourcecommons.net/community/).

BTW, fixed the redirect bug and pulled some text improvements from your closed PR.
As we have patterns living on the external site, IMHO we should open their link in a separate tab to keep the audience on the main site.

**Comment by spier** [comment]
> My thoughts on this point:
> Under the learning section, we should keep only the content produced by the working group. I mean the pattern itself from Patterns WG, the learning path from the corresponding WG.
> Other info: office-hours, organization moments, etc should live under the [community section](https://innersourcecommons.net/community/).
> 
> BTW, fixed the redirect bug and pulled some text improvements from your closed PR.
> As we have patterns living on the external site, IMHO we should open their link in a separate tab to keep the audience on the main site.

Reminder to self:
⬆️   this was in response to this comment on #74

> I am having second thoughts on this intermediate pattern page. Or at the very least I don't know where it logically belongs on the site.
> 
> * The **Learning Path page** (https://innersourcecommons.net/learn/learning-path/) shows the actual learning path, and doesn't talk about the working group as such.
> * The **Patterns page** that I am creating in this PR points to various resources related to the patterns WG, as the main artifact of the WG (the book and github repo) don't live inside our website. => should this page really life in the Learn section?

**Comment by spier** [comment]
> Under the learning section, we should keep only the content produced by the working group. I mean the pattern itself from Patterns WG, the learning path from the corresponding WG.

Playing that thought through, the content produced by the Patterns WG is:
* the Patterns book - starting point for readers
* the Patterns GitHub repo - starting point for contributors and readers that even want to read unfinished patterns

I think it is best to focus on the book overall, as I think that most people will first start as readers, and only later become contributors (if they want).

I find the current way of linking directly from the menu to an external site (the [gitbook](https://innersourcecommons.gitbook.io/innersource-patterns/)) a bit strange.

What do you think about linking from the menu item `Learn / Patterns` to https://innersourcecommons.net/learn/books/innersource-patterns/?

That would mean that there are two navigation paths to reach that book page:
* `Learn / Patterns`
* `Learn / Book / ...`

----

> Other info: office-hours, organization moments, etc should live under the [community section](https://innersourcecommons.net/community/).

I can do that. So I would basically move the page that I created in #74 below the Community menu, and modify the page a bit to focus more on the WG, and less on the book itself.

That Community menu entry would then look like this:
* Community
   * InnerSource in Action
   * Patterns Working Group 

One possible challenge with that is that the other WGs might not have dedicated WG-pages immediately. However it might motivate them to create such pages? :)

This website information architecture topic is harder than I thought! :)

**Comment by voborgus** [comment]
I would propose you not create a separate page (at least for now) and enrich information needed right on the community page: https://innersourcecommons.net/community/

The Office-hours google calendar widget contains all WGs community meetings, so therefore it is actual not only for the Patterns WG. 

> What do you think about linking from the menu item Learn / Patterns to https://innersourcecommons.net/learn/books/innersource-patterns/?

Yeah, this will be better rather than now I think.

**Comment by spier** [comment]
@voborgus I will try that as you suggested.

However I don't know what you are proposing with regards to the Patterns Office Hours calendar widget?
I cannot integrate that on https://innersourcecommons.net/community/ as there isn't enough space (or rather it would look strange). Any idea where I might put it?

Or are you suggesting to leave the calendar widget away entirely?  
The potential issue with that is that we then don't have a way to advertise for the office hours any more.
I can try to find out with others in the Patterns community if they would be ok with this approach for now.

**Comment by voborgus** [comment]
I think the schedule can live in a separate section after explanations how we work:
<img width="834" alt="Schedule placement" src="https://user-images.githubusercontent.com/9394918/109424576-26cf4b80-79f5-11eb-90ac-35ba3b58f9d2.png">

Good title, small intro paragraph and voila. How do you think @spier ?

**Comment by voborgus** [comment]
And as I see this calendar contains not only patterns office hours events: so it may be useful for all working groups :)

**Comment by spier** [comment]
> And as I see this calendar contains not only patterns office hours events: so it may be useful for all working groups :)

Yeah, I understand the purpose of not tying the calendar to the Patterns WG only.
The calendar even contains the board meetings, which aren't open to the general public from what I know?
But maybe that's a problem for another day.

I will try to get the calendar integrated as you were suggesting.

**Comment by spier** [comment]
This is done now!
