### ISSUE TITLE
Integrate the books section

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/innersourcecommons.net#49]
**Is your feature request related to a problem? Please describe.**

We have a collection of books at https://innersourcecommons.org/resources/books/ that would be great to get ported to the new site.

InnerSource Books

- Getting Started With InnerSource
- Understanding the InnerSource Checklist
- Adopting InnerSource - Principles and Case Studies
- Managing InnerSource Projects
- InnerSource Patterns

**Describe the solution you'd like**

The place in the new site for this seems to be https://innersourcecommons.net/learn/books/?

I would suggest to use the cover images of the books on the overview page. That way we show all books side-by-side, much like in a bookshelf. Will be really pretty :)

**Comment by spier** [comment]
@dicortazar any suggestion for a cover image that we could use for the "Managing InnerSource Projects",  even if just as a temporary solution?

**Comment by spier** [comment]
Just noticed that the "Getting Started With InnerSource" book that used to be available at http://www.oreilly.com/programming/free/getting-started-with-innersource.csp cannot be reached through that URL any more. Does anybody know what might have happened there?

**Comment by voborgus** [comment]
Available here: https://innersourcecommons.net/learn/books/
