### ISSUE TITLE
Ensure the Learning Path section OK to go live 

### ISSUE THREAD

**Issue by voborgus** [InnerSourceCommons/innersourcecommons.net#51]
**Is your feature request related to a problem? Please describe.**
We need to have a green light from the Learning Path working group on their section for moving the current site to production.

**Describe the solution you'd like**
Ask approvement.

**Comment by claredillon** [comment]
What's required to close this? The new Learning Path page looks fab! :)

**Comment by voborgus** [comment]
They have to decide: do they need to make translations work before we'll flip the sites or not. Info from here: https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/362

**Comment by voborgus** [comment]
Thanks to @tsadler1988, translations are live on the site:

https://innersourcecommons.net/learn/learning-path/

Currently known bugs:

* Menus are hidden when the language is changed. (will fix that later)
* Links in the breadcrumb resets the language setup. (it's harder to fix because we have only LP content translated currently)
* Description of the courses is in English right now since the index pages are not translated. (It's correct only for Russian now)
[A bad example](https://github.com/InnerSourceCommons/innersourcecommons.net/blob/master/content/learn/learning-path/introduction/_index.ja.md), [a good example](https://github.com/InnerSourceCommons/innersourcecommons.net/blob/master/content/learn/learning-path/introduction/_index.ru.md). Will be fixed after all translations will be done in a separate issue in the LP project.

Any considerations are we ready to go to production from the Learning Path point of view?

**Comment by voborgus** [comment]
The first and the second problems fixed.

**Comment by claredillon** [comment]
Update from yesterday's Learning Path meeting. The LP working group decided that they needed index pages for the different languages (saying translations coming soon, where the translations not available) before we go live. This will address the confusion that may arise if people change the language and don't see _any_ change in the index page. @tsadler1988 is working on creating the index files... when they are complete, the LP are ready to go.

**Comment by clcoffey** [comment]
I am looking into this and I would like to check the best way to move forward. My preference is for the second option as with the first one you don't really see the added Translation comming soon text.

![screencapture-localhost-1313-de-learn-learning-path-2021-03-18-14_10_09](https://user-images.githubusercontent.com/78749459/111640345-04f70680-87f4-11eb-9e8e-20b8b3a3685b.png)

![screencapture-localhost-1313-de-learn-learning-path-2021-03-18-14_10_50](https://user-images.githubusercontent.com/78749459/111640358-088a8d80-87f4-11eb-92cc-74be61a1f5e3.png)

**Comment by claredillon** [comment]
I think we need to leave the text in place (for it to be translated). I would recommend appending a notice something like the following to each piece of text...

**Introduction**
 _[**This text will be translated into German shortly**.]_Check out the Introduction to learn about the types of problems where InnerSource can help, how to do it, the types of benefits you can expect to see by participating, and the underlying principles that make it all work.

**Comment by tsadler1988** [comment]
Looks great! Thanks @voborgus, @claredillon, @clcoffey.
