### ISSUE TITLE
Save important links from breaking

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/innersourcecommons.net#54]
**Is your feature request related to a problem? Please describe.**

If we release the new site, the links that are pointing to pages on the old site will break. 
- links indexed by Google and other search engines
- links used in presentations, blog posts, etc.

**Describe the solution you'd like**

Can we determine which links we would like to keep functional, and create redirects for them?

While I don't think that we have to keep all old links functional, saving some of the important ones that are creating inbound traffic for the old site would be worthwhile saving. Possible issue: We might not know which ones are important.

**Comment by spier** [comment]
Yesterday I found that even some of the InnerSource books have  links to innersourcecommons.org. Didn't consider books as sources of inbound links but it makes sense of course :)

e.g. the book "Understanding the InnerSource Checklist" has links to:

* http://innersourcecommons.org/training - doesn't even exist on the old site any more
* http://innersourcecommons.org/patterns => redirects to https://github.com/InnerSourceCommons/InnerSourcePatterns
* ...

**Comment by voborgus** [comment]
According [this](https://github.com/InnerSourceCommons/innersourcecommons.org/tree/master/pages), we have redirects:

path | redirect to
--- | --- 
 /youtube/ | https://www.youtube.com/channel/UCoSPSd6Or4F_vpjo4SmyoEA 
/wiki/ | https://github.com/InnerSourceCommons/innersourcecommons.org/wiki 
/slackinvite/ | https://innersourcecommons-inviter.herokuapp.com/
/slack/ | https://innersourcecommons-inviter.herokuapp.com/ 
/patterns/ | https://github.com/InnerSourceCommons/InnerSourcePatterns
/patterns-officehours/ | https://innersourcecommons.org/resources/patternsofficehours/
/learningpath/ | https://innersourcecommons.org/resources/learningpath/ 
/isc-101/ | https://docs.google.com/document/d/1VvdgN2b0MAd7wXeNGUFaeYviguS34oBioX0XavNtbyY
/ggroup/ | https://groups.google.com/forum/#!forum/innersource-commons 
/gdrive/ | https://drive.google.com/drive/folders/0B2FGN9Kd_fgSMDhJU1Nna0Njbm8

We should decide which links we want to keep and create [redirects](https://github.com/InnerSourceCommons/innersourcecommons.net/tree/master/content/redirects) for them.
And of course, can create a  `/training/` and lead somewhere.

**Comment by spier** [comment]
Should we consider this ticket part of the MVP?
My vote is 👍

**Comment by voborgus** [comment]
It's not a big deal, let's consider this as MVP.
Will be good to decide the list of redirects we want to keep on the next marketing sync call.

**Comment by spier** [comment]
It's not just the existing redirects on the old site that would break though.

We would also have to check if any content that used to live at `isc.org/old/page` now lives at `isc.net/some/other/page`. Because those old links would also break.

Determining which links will break might be tricky in the call itself. We can discuss the general approach we want to take of course. And I don't expect that our approach will be "don't worry, just break all links". That would be the easiest of course but I would think it does too much harm for users and SEO.

I don't know how this is typically done when websites are migrated. However I am thinking something like 
* creating a full URL tree of all pages on the old site
* mapping that to the new site
* then deciding which links to redirect, and which ones to kill

Would that be useful? Has anybody done this before?

**Comment by voborgus** [comment]
All links on the old site according to the sitemap:
https://pastebin.com/raw/wi1i6A6Y

**Comment by voborgus** [comment]
If we want to support the old URLs we can make redirects with these parameters on each page header:
```
aliases:
  - /old-url/
```

I would propose:

* Ask learning-patherers do they want to keep the old URLs working and if yes ask them to fill this field in all automatically-generated files.

* Create redirects for some of the manually created redirects from the old site. 
** `/slack/` – to the slack herokuapp
* Create aliases in the existing pages for:
** `/learningpath/` and `/resources/learningpath/` – to the LP root
** `/patterns/` – to the patterns book
** `/isc-101/` – to the community or about section
** `/resources/books/` – to the books
** `/board/` – to the board
** `/resources/books/adoptinginnersource/` – to the book
** `/getting-started/` – to the book
** `/checklist/` – to the book
* And drop the rest urls:
** `/slackinvite/`
** `/patterns-officehours/`
** `/ggroup/`
** `/wiki/`
** `/gdrive/`
** `/youtube/`
** `/news/`
** `/board/...terse notes items`
** `/events/...all events pages`
** `/resources/articles/`
** `/events/conduct/`
** `/contribute/`
** `/contact/`
** `/search/`
** ... and all URLs not included here...

**Comment by spier** [comment]
These are the 196 URLs that google has indexed for the old innersourcommons.org site:
https://www.google.de/search?q=site:innersourcecommons.org

**Comment by claredillon** [comment]
Agreed at marketing meeting :
- Assess risk to Google ranking
- Identify any we need to redirect
- Approve list  of URLS to drop

**Comment by claredillon** [comment]
I've had a call with a friend who runs a web dev/design company and is often tasked with optimising sites for SEO to find out more. Some points I learned:
- Changing the site architecture will cause Google issues - so we should take steps to mitigate that.
- The re-directs are not necessarily the thing that will help - as they can often confuse Google crawler, and cause longer load pages which may _decrease_ our page ranking in itself. 
- There are other basic technical things we can do to ensure that the site gets ranked better, and we can actually notify Google to let them know we've changed the site to get them to crawl it again and re-index.

The upshot is - no real benefit in doing lots of redirects - so we don't have to do that. 

The other great news is that he has offered to run our sites through his SEO analysis tool to do a report on .org and .net sites to see strengths/weaknesses and help us with a plan to improve SEO over time. Should have that shortly to review.

**Comment by claredillon** [comment]
Comment above addresses the links indexed by Google and other search engines. 
For the purposes of not breaking old links that may exist in other sites/resources, I agree with Dmitrii's proposal above.

**Comment by claredillon** [comment]
I would add that we should recommend to the learning path community to consider the potential risk of dropping in Google rankings if we create re-directs for each page against the risk of someone following an old link to a particular bit of LP content. That is, my recommendation would be that we do not create individual redirects for LP content.

**Comment by voborgus** [comment]
Aliases from my proposition now live on the site, what else should be done for closing this?

**Comment by voborgus** [comment]
Agree on the meeting that's enough at least for MVP.
