### ISSUE TITLE
Create an "intro text" explaining the purpose of the Board

### ISSUE THREAD

**Issue by voborgus** [InnerSourceCommons/innersourcecommons.net#55]
**Is your feature request related to a problem? Please describe.**
Unclear what for the Board exists.

**Describe the solution you'd like**
Create a one-paragraph text at the top of the page explaining the purpose of the board and put it [here](https://innersourcecommons.net/about/board/).

**Comment by claredillon** [comment]
I will add this in this evening. 

Recommend also moving the minutes/bylaws etc to the bottom of the board page - they are only there as a legal requirement .

**Comment by clcoffey** [comment]
I can do this now.

**Comment by clcoffey** [comment]
Actually Dmitrii I can see you changed the page into an index page and I am assuming that is why the list comes up at the top now. I am not sure how to place it at the bottom in this format so I will leave it up to you. I will just add the paragraph at the top of the board members.

**Comment by voborgus** [comment]
@clcoffey I moved it to the top because it was hidden previously. If user will not scroll the page till the end, he will miss this information. If you think we need to have this at the bottom, I can move it easily.

Since the meeting information currently generated automatically I moved this block to layout. Info taken from the files exists in the folder. 👍🏻 thanks for moving this forward!

**Comment by voborgus** [comment]
moved things to the bottom

**Comment by clcoffey** [comment]
Brilliant! Thanks Dmitrii!

**Comment by claredillon** [comment]
I added new proposed text in Cristina's fork (is that the right process?). It includes the legal reasons why a board is necessary and slight change to the text (board is elected by Membership).

**Comment by voborgus** [comment]
Yeah, you're awesome!
