### ISSUE TITLE
Link are not consistently styled

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/innersourcecommons.net#63]
**Describe the bug**
Links are not consistently styled. They get different colors. See screenshot.

![link colors 2021-02-23 at 21 12 39 ](https://user-images.githubusercontent.com/163029/108903491-a50aa700-761d-11eb-827b-25fc9d047e57.JPG)

**Expected behavior**

All links should have the same font color.

**Comment by voborgus** [comment]
Fixed

**Comment by spier** [comment]
@voborgus thanks for the quick fix for the issue described in here. I checked the commit history but couldn't spot the exact commit that fixed this.

I think we still have two issues related to links:
- the links on some pages don't work (e.g. http://localhost:1313/learn/books/innersource-patterns/) (bug)
- the links don't change style on hover (mouse-over) => might not be clear for users that they are links? (we have to decide if we consider this a usability issue or not)

**Comment by voborgus** [comment]
Sorry for the non-linked commit. Fixed the content links (ex. on books pages).

It was done with the custom CSS style [here](https://github.com/InnerSourceCommons/innersourcecommons.net/blob/master/assets/scss/_custom.scss) at the top.
