### ISSUE TITLE
More Videos Button on front page goes to wrong place

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/innersourcecommons.net#65]
**Describe the bug**
The More Videos button on the home page point to Leroy Merlin's YT channel.

**Expected behavior**
Should go to here: https://www.youtube.com/channel/UCoSPSd6Or4F_vpjo4SmyoEA

**Additional context**
Couldn't see how/where to edit the link from the more-videos-button

**Comment by voborgus** [comment]
whoops :) fixed. it was here: https://github.com/InnerSourceCommons/innersourcecommons.net/blob/master/layouts/shortcodes/more-videos-button.html
