### ISSUE TITLE
Integrate the Mailchimp Mailing list code 

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/innersourcecommons.net#68]
**Is your feature request related to a problem? Please describe.**
Need to make the Announcement mailing list sign up work.

**Describe the solution you'd like**

- [x] Create Mailchimp account with ISC ID
- [x] identify the code that can be used on the ISC website (there are various options on the Mailchimp site)
- [x] Add it to the Stay Connected section on Home page
- [x] -Add it to the Stay Connected section on community Page
- [x] Add it to the Stay Connected section on Contact Us page

**Additional context**

**Comment by claredillon** [comment]
The Mailchimp account is created. Will work this afternoon on getting the embedded code required for the website.

**Comment by claredillon** [comment]
This is the code from Mailchimp. 


<link href="//cdn-images.mailchimp.com/embedcode/horizontal-slim-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; width:100%;}
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://innersourcecommons.us1.list-manage.com/subscribe/post?u=0363fb06e6a59d48c6e260f1b&amp;id=97224b5ff2" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	
	<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
    
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_0363fb06e6a59d48c6e260f1b_97224b5ff2" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>

**Comment by voborgus** [comment]
Works [here](https://innersourcecommons.net/community/) and [here](https://innersourcecommons.net/).

Created a new `{{< contact-form >}}` tag for the form placement.

Currently on the plain HTML, in the future to be improved to Ajax JS way to make the process of subscription fancier.

**Comment by claredillon** [comment]
The process is seamless - thanks @voborgus 

I note though, it doesn't do the usual "confirm your subscription from your email" process. Is that something we need do you think?

**Comment by voborgus** [comment]
I don't know, seems this is the default behavior of the MailChimp.
And maybe we should insert something for GDPR compliance (or not :) )

**Comment by claredillon** [comment]
Contact us page now live. Closing this issue. Will open a new (non MVP issue) to investigate email confirmation with Mailchimp.
