### ISSUE TITLE
Create / update the Learn index page. 

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/innersourcecommons.net#71]
**Is your feature request related to a problem? Please describe.**
Create a page that gives an overview of the the various learning resources.

**Describe the solution you'd like**
The page should list the various learning resources (Learning Path, Patterns, Events, Books).
The text should help a new visitor understand the differences between the various resources. 
The tone should be inviting and encourage new visitors to explore. 

Events is optional to include here - but I think it adds to the set of options. 

**Additional context**
Proposed text is here: https://github.com/InnerSourceCommons/innersourcecommons.net/pull/67
It needs new images.

**Comment by claredillon** [comment]
I proposed a new page above - but @voborgus would it work just as well/better to include the text I propose in index files of the folders? That would keep the current layout. 

A better approach?

**Comment by voborgus** [comment]
Currently, the content in the Learn base page generated automatically based on the folder structure. This behavior is true for the rest pages on this section, for example, books or learning path.

I can easily flip the content on this page to your manually placed content if we decide to go with that way.

**Comment by voborgus** [comment]
OR we can use the descriptions field for your text and do the same with automatically generated pages. 🙂

**Comment by claredillon** [comment]
Yes - and it would probably be more consistent therefore to leave the layout as is. If I change the intro text (e.g. for Books:
A collection of books about InnerSource. Produced directly by or in association with the InnerSource Commons.) - am I right in saying the only place it changes is then the Learn Base page?

**Comment by voborgus** [comment]
> Yes - and it would probably be more consistent therefore to leave the layout as is. If I change the intro text (e.g. for Books:
A collection of books about InnerSource. Produced directly by or in association with the InnerSource Commons.) - am I right in saying the only place it changes is then the Learn Base page?

With the current layout – yes. But this can be changed with a little code.

**Comment by voborgus** [comment]
I mean something like this with the default layout:

![image](https://user-images.githubusercontent.com/9394918/109031168-823bc980-76d5-11eb-9eff-9468630c0444.png)

Or we can change to the manually crafted content with the homepage-styled sections.

**Comment by voborgus** [comment]
The first choice currently available here: https://innersourcecommons.net/learn/

**Comment by claredillon** [comment]
That looks really nice, @voborgus. Thanks!

I don't mind leaving the events page off... But could we included the overall intro text somehow? (Not an MVP ask, so will close this issue regardless).
