### ISSUE TITLE
Check Working Groups/Board are OK with Calendar going live.

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/innersourcecommons.net#89]
**Is your feature request related to a problem? Please describe.**
I don't believe the calendar has been published publicly before. Might be good to check with working groups and board to make sure the contents are appropriate for public view. 

**Describe the solution you'd like**
For example, the minutes doc is linked from the Marketing WG calendar, and those minutes are under Chatham House Rules. We can not include them there in the future, to resolve this issue - but it might require process changes in other groups. E.g. The board meeting includes the meeting link, which is not open. Suggest we double check before including the calendar on the website. 

**Additional context**
Is including the calendar necessary for MVP? Can we remove while we do this check?

**Comment by claredillon** [comment]
Secondary issue is that most meetings currently set up to allow you to see other guest participants (and email addresses). Think we can't include this for privacy reasons.

**Comment by claredillon** [comment]
Noting that the issue doesn't just effect new meetings moving forward - but would require scrubbing of past meetings.

**Comment by voborgus** [comment]
I'm OK to hide the calendar for the MVP run. Just for info, we currently have one on the old site (will not post the link here:))

**Comment by claredillon** [comment]
Closing this issue for now then.

**Comment by spier** [comment]
FYI the calendar has been public on the old site already, so the initial assumption in the issue is wrong:
https://innersourcecommons.org/resources/patternsofficehours/
