### ISSUE TITLE
Port Press Releases

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/innersourcecommons.net#92]
**Is your feature request related to a problem? Please describe.**

The old site contains a section for press releases. It only contains a single item though :)
https://innersourcecommons.org/news/

**Describe the solution you'd like**

Do we want to port this to the new site?

**Comment by claredillon** [comment]
I would agree. We can keep it as a doc on gDrive (for posterity) but not necessary on new site and I can confirm it's not legally required. All planned press can happen through social.

**Comment by spier** [comment]
Sounds good. Closing. This issue then.
