### ISSUE TITLE
Add Privacy Policy link to the Footer

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/innersourcecommons.net#95]
The website should have a Privacy Policy link in the footer so it is easy to find and access.

**Comment by voborgus** [comment]
Hi @clcoffey, I've added the link right after PR merge:
 
 
![image](https://user-images.githubusercontent.com/9394918/110837959-f5873300-82b2-11eb-8184-6490b47eb31d.png)

**Comment by clcoffey** [comment]
Brilliant! Thanks Dmitrii!
